export type Preset = {
  id: string;
  name: string;
  en: string;
  version: string;
  category: "电影" | "夜色" | "人像" | "风景" | "黑白";
  image: string;
  ratio: string;
  description: string;
  note: string;
  tags: string[];
  palette: string[];
  link: string;
  number: string;
};

const repoBase =
  "https://github.com/ReefRuan/tonerelay-style-packs/tree/main/packages";
const asset = (name: string) => `${import.meta.env.BASE_URL}presets/${name}`;

export const presets: Preset[] = [
  {
    id: "blue-hour-relay",
    name: "蓝时回声",
    en: "BLUE HOUR RELAY",
    version: "v1.2",
    category: "夜色",
    image: asset("blue-hour-stair.jpg"),
    ratio: "4 / 5",
    description: "把将暗未暗的蓝留住，让很小的暖光成为画面的呼吸。",
    note: "冷调阴影、克制高光与轻微银盐颗粒。适合建筑、雨后与安静的远景。",
    tags: ["Blue Hour", "Cinematic", "Cool"],
    palette: ["#23384d", "#50718f", "#9bb3c4", "#d49b5f"],
    link: `${repoBase}/blue-hour-relay`,
    number: "01",
  },
  {
    id: "chrome-weekend",
    name: "铬色周末",
    en: "CHROME WEEKEND",
    version: "v1.0",
    category: "电影",
    image: asset("classic-chrome.jpg"),
    ratio: "3 / 2",
    description: "低饱和城市色彩，像一卷在周末慢慢拍完的负片。",
    note: "压低红色亮度，保留金属与皮革的层次；适合街道、旧车与日常旅行。",
    tags: ["Classic", "Street", "Muted"],
    palette: ["#34383a", "#7b837c", "#a9a185", "#c9c3b4"],
    link: `${repoBase}/chrome-weekend`,
    number: "02",
  },
  {
    id: "last-night-bus",
    name: "末班夜车",
    en: "LAST NIGHT BUS",
    version: "v1.4",
    category: "夜色",
    image: asset("night-bus.jpg"),
    ratio: "7 / 5",
    description: "潮湿街灯、深色玻璃，以及午夜仍然发亮的红。",
    note: "保护霓虹高光，阴影带轻微青绿偏色。适合城市夜景和隔窗拍摄。",
    tags: ["Night", "Neon", "Grain"],
    palette: ["#11161b", "#27434c", "#9b493d", "#e0ad72"],
    link: `${repoBase}/last-night-bus`,
    number: "03",
  },
  {
    id: "rain-on-glass",
    name: "雨落玻璃",
    en: "RAIN ON GLASS",
    version: "v0.9",
    category: "电影",
    image: asset("heavy-rain.jpg"),
    ratio: "3 / 2",
    description: "让灰色不再扁平，把雨天拆成许多层很慢的颜色。",
    note: "柔化对比并抬起黑位，偏冷的中间调仍保留肤色空间。",
    tags: ["Rain", "Soft", "Low Contrast"],
    palette: ["#465158", "#79858a", "#abb4b4", "#d8d5c9"],
    link: `${repoBase}/rain-on-glass`,
    number: "04",
  },
  {
    id: "c200-starlight",
    name: "星野 C200",
    en: "C200 STARLIGHT",
    version: "v1.1",
    category: "夜色",
    image: asset("milky-way.jpg"),
    ratio: "9 / 8",
    description: "颗粒明显但不粗暴，给深夜留一点旧底片的温度。",
    note: "蓝紫暗部、温暖地平线和受控的星点锐度，适合夜空与旷野。",
    tags: ["Stars", "C200", "Analog"],
    palette: ["#111629", "#29335c", "#6b7195", "#d0a16a"],
    link: `${repoBase}/c200-starlight`,
    number: "05",
  },
  {
    id: "toscana-paper",
    name: "托斯卡纳纸页",
    en: "TOSCANA PAPER",
    version: "v1.3",
    category: "风景",
    image: asset("toscana.jpg"),
    ratio: "1 / 1",
    description: "暖土、低云与旧纸一样的黄色，把风景压进一本旅行册。",
    note: "柔和绿色、奶油高光与陶土红，适合乡野、建筑和午后静物。",
    tags: ["Warm", "Travel", "Paper"],
    palette: ["#5d6044", "#a08658", "#c6aa72", "#ece2c4"],
    link: `${repoBase}/toscana-paper`,
    number: "06",
  },
  {
    id: "quiet-corridor",
    name: "走廊日光",
    en: "QUIET CORRIDOR",
    version: "v1.0",
    category: "人像",
    image: asset("sunny-corridor.jpg"),
    ratio: "3 / 2",
    description: "让窗边的肤色和墙面都拥有不过分明亮的暖意。",
    note: "高光缓降、清淡阴影和非常轻的橙色漂移，适合室内与自然光人像。",
    tags: ["Portrait", "Window", "Gentle"],
    palette: ["#6d5e50", "#ad9072", "#d6b98f", "#f0e2c8"],
    link: `${repoBase}/quiet-corridor`,
    number: "07",
  },
  {
    id: "malacca-memory",
    name: "马六甲记忆",
    en: "MALACCA MEMORY",
    version: "v1.2",
    category: "电影",
    image: asset("malacca.jpg"),
    ratio: "3 / 2",
    description: "南方午后的褪色红与青，把旅行变成一张旧明信片。",
    note: "降低数字锐利感，红色略向砖色偏移，绿色保持潮湿与通透。",
    tags: ["Travel", "Faded", "Postcard"],
    palette: ["#355e60", "#8d735d", "#b45e4d", "#dfc79e"],
    link: `${repoBase}/malacca-memory`,
    number: "08",
  },
  {
    id: "moss-after-rain",
    name: "雨后苔生",
    en: "MOSS AFTER RAIN",
    version: "v0.8",
    category: "风景",
    image: asset("growing.jpg"),
    ratio: "3 / 2",
    description: "深绿不必发黑，细小生命仍能从阴影中被看见。",
    note: "苔绿与褐色分离，局部微对比更清晰，适合植物、林地和近摄。",
    tags: ["Green", "Nature", "Macro"],
    palette: ["#203d2e", "#4f6c43", "#819064", "#c6b98f"],
    link: `${repoBase}/moss-after-rain`,
    number: "09",
  },
  {
    id: "bridge-silence",
    name: "桥上静默",
    en: "BRIDGE SILENCE",
    version: "v1.0",
    category: "黑白",
    image: asset("waiting-bridge.jpg"),
    ratio: "3 / 2",
    description: "不追求纯黑纯白，只保留雾、钢与远处的人。",
    note: "宽容中灰、细颗粒与低锐度边缘，适合建筑、街头与叙事人像。",
    tags: ["Monochrome", "Documentary", "Soft"],
    palette: ["#222324", "#5d5f5e", "#999994", "#dedbd1"],
    link: `${repoBase}/bridge-silence`,
    number: "10",
  },
  {
    id: "sunset-negative",
    name: "落日负片",
    en: "SUNSET NEGATIVE",
    version: "v1.5",
    category: "风景",
    image: asset("sunset.jpg"),
    ratio: "3 / 2",
    description: "收住黄昏最容易失控的颜色，让天空仍然像空气。",
    note: "压缩高光，橙红不过饱和，暗部带少量紫蓝。适合逆光与大光比风景。",
    tags: ["Sunset", "Highlight", "Landscape"],
    palette: ["#383351", "#7b5570", "#c87563", "#f1bd7d"],
    link: `${repoBase}/sunset-negative`,
    number: "11",
  },
];

export const categories = ["全部", "电影", "夜色", "人像", "风景", "黑白"] as const;
export type Category = (typeof categories)[number];
